name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the application is affected?
      options:
        - Home Page
        - Q&A Board (/questions)
        - Interactive Quiz (/interactive)
        - Admin Dashboard (/admin)
        - Sorting Demo (/sorting)
        - Maze Demo (/mazes)
        - Patterns Demo (/patterns)
        - Object Detection (/object-detection)
        - Wheel Demo (/wheel)
        - Authentication (Login/Logout)
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide relevant environment details
      placeholder: |
        - OS: [e.g., macOS, Windows, Linux]
        - Node version: [e.g., 22.x]
        - Browser version: [e.g., Chrome 120]
      render: markdown
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Screen Recordings
      description: If applicable, add screenshots or recordings to help explain the problem
      placeholder: Drag and drop images/videos here
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: If applicable, paste any relevant console errors or logs
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
